on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: meihuisu/hello-world-composite-run-steps-action/.github/actions@v8
      with:
        ref: toPython3
        who-to-greet: 'Mona from ucvm_plotting'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash

