name: ucvm_plotting-ci

on: [push]

jobs:
  ucvm_plotting-build:
    runs-on: ubuntu-latest
    name: A job to build ucvm_plotting
    steps:
    - uses: actions/checkout@v2
    - run: ( echo "UCVM_PLOTTING_PATH=$RUNNER_WORKSPACE/ucvm_plotting" >> $GITHUB_ENV )
      shell: bash
#    - id: build-ucvm
#      uses: SCECcode/UCVMC/.github/actions@action1
#      with:
#        target-models: 'cvmh'
#    - run: echo build-log ${{ steps.build-ucvm.outputs.build-log }}
#      shell: bash
    - name: Set up Python 2.7.17
      uses: actions/setup-python@v2
      with:
        python-version: '2.7.17'
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
#    - name: Set up Conda
#      uses: s-weigand/setup-conda@v1
#      with:
#        update-conda: true
#        python-version: '2.7.17'
#        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python
    - run: which conda
    - run: python -V
    - run: which python2
    - run: python2 -V
    - name: bring in basemap
      run: conda install matplotlib basemap basemap-data-hires
    - name: test basemap
      run: (cd $UCVM_PLOTTING_PATH; ./.github/scripts/test_basemap.py)
#    - name: build-self
#      run: (cd $UCVM_PLOTTING_PATH; ./.github/scripts/ucvm_plotting-build.sh)
#      shell: bash
#    - name: test plotting
#      run: (cd $UCVM_PLOTTING_PATH; ./.github/scripts/ucvm_plotting-test.sh)
#      shell: bash
