name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    container: docker://mpihuisu/py2ucvm:1.1
    steps:
    - uses: actions/checkout@v2
    - run: |
          source ~/.bashrc
          export > $HOME/query.txt
          env >> $HOME/query.txt
          ucvm_query -H  >> $HOME/query.txt
       shell: bash
    - run: cat $HOME/query.txt

