on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: build
      uses: SCECcode/UCVMC/.github/actions@action1
      with:
        target-models: 'cvmh'
    - run: echo build-log ${{ steps.build.outputs.build-log }}
      shell: bash

