name: ucvm_plotting-ci

on: [push]

jobs:
  ucvm_plotting-build:
    runs-on: ubuntu-latest
    name: A job to build ucvm_plotting
    steps:
    - uses: actions/checkout@v2
    - run: ( echo "UCVM_PLOTTING_PATH=$RUNNER_WORKSPACE/ucvm_plotting" >> $GITHUB_ENV )
      shell: bash
    - id: build-ucvm
      uses: SCECcode/UCVMC/.github/actions@action1
      with:
        target-models: 'cvmh'
    - run: echo build-log ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - run: env
      shell: bash
    - run: ls $UCVM_PLOTTING_PATH/ucvm_plotting 
      shell: bash
    - id: build-self
      run: (cd $UCVM_PLOTTING_PATH; ./.github/scripts/ucvm_plotting-build.sh)
      shell: bash
    - run: ls
      shell: bash
 
